version: "3.9"
networks:
  reverse-proxy:
    driver: overlay
    external: true
    
volumes:
  saves:
  mods:

services:
  factorio:
    image: factoriotools/factorio:1.1.102
    hostname: factorio
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.udp.routers.factorio.entrypoints=factorio" #entrypoint->router
        - "traefik.udp.routers.factorio.service=factorio" #router -> service
        - "traefik.udp.services.factorio.loadbalancer.server.port=34197" #port of service
    networks:
     - reverse-proxy
    volumes:
     - type: bind
       source: ./config
       target: /factorio/config/
     - type: volume
       source: saves
       target: /factorio/saves/
     - type: volume
       source: mods
       target: /factorio/mods/
    environment:
      UPDATE_MODS_ON_START: "TRUE"
      GAME_PASSWORD: "${GAME_PASSWORD}"
      TOKEN: "${TOKEN}"
      GENERATE_NEW_SAVE: "TRUE"
      SAVE_NAME: "Test_server_save.zip"
      #LOAD_LATEST_SAVE: "TRUE"
