version: "3.9"
networks:
  reverse-proxy:
    driver: overlay
    external: true
      
services:
  factorio:
    image: factoriotools/factorio:latest
    hostname: factorio
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.udp.routers.factorio.entrypoints=factorio" #entrypoint->router
        - "traefik.udp.routers.factorio.service=factorio" #router -> service
        - "traefik.udp.services.factorio.loadbalancer.server.port=34197" #port of service
    networks:
     - reverse-proxy
    volumes:
     - type: bind
       source: ./config
       target: /factorio/config/
    environment:
      UPDATE_MODS_ON_START: "TRUE"
      GAME_PASSWORD: "${GAME_PASSWORD}"
      TOKEN: "${TOKEN}"
