version: "3.9"
networks:
  reverse-proxy:
    driver: overlay
    external: true
      
services:
  factorio:
    image: factoriotools/factorio:1.1.99
    hostname: factorio
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.factorio.rule=Host(`factorio.actuary.dev`)"
     - "traefik.http.services.factorio.loadbalancer.server.port=80"
    networks:
     - reverse-proxy
    ports:
     - "80:80/udp"
     - "80:80/tcp"
    volumes:
     - /data/factorio:/factorio
     - ./config/server-settings.json:/server-settings.json
     - ./config/map-gen-settings.json:/map-gen-settings.json
     - ./config/map-settings.json:/map-settings.json
     - ./config/server-whitelist.json:/server-whitelist.json
    environment:
      UPDATE_MODS_ON_START: "TRUE"
      USERNAME: "${USERNAME}"
      TOKEN: "${TOKEN}"
