version: "3.9"

services:
  factorio:
    image: factoriotools/factorio:1.1.99
    hostname: factorio
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.factorio.rule=Host(`factorio.actuary.dev`)"
     - "traefik.http.services.factorio.loadbalancer.server.port=34197"
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - type: bind
       source: ./
       target: /factorio
       bind:
         propagation: shared
         nonrecursive: true
    environment:
      UPDATE_MODS_ON_START: "TRUE"
      USERNAME: "${USERNAME}"
      TOKEN: "${TOKEN}"
