name: 'Deploy stack'
on:
  workflow_dispatch:
  push:
    branches:
      - main   
      - init
jobs:
  redeploy-service:
    runs-on: [HardwareName]
    env:
      USERNAME: ${{ vars.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'alexandertroyscott/factorio'
          ref: 'main'
      - name: Remove and redeploy services
        run: |
          SERVICES=("headless_factorio") 
          for SERVICE_NAME in "${SERVICES[@]}"; do
            if docker service ls | grep -q $SERVICE_NAME; then
              docker service rm $SERVICE_NAME;
              echo "Service $SERVICE_NAME removed."
            else echo "Service $SERVICE_NAME is not running."
            fi
          done
      - run: chmod -R 777 ./
      - run: docker stack deploy -c factorio.yaml headless
